name: Publish image to Docker Hub

on:
  workflow_dispatch:

jobs:
  publish_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build . -t temrario/dockerpract3:latest

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login --username temrario --password-stdin

      - name: Push Docker image
        run: |
          docker push temrario/dockerpract3:latest
